[package]
name = "rao-forward"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.44", features = ["derive"] }
ndarray = "0.16.1"
rao = "0.1.11"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.14"
toml = "0.9.5"
zernike = "0.2.1"
