[[disturbances]]

[disturbances.Zernike]
id = "dm"
coeffs = [1.0, 2.0, 3.0]
radius = 4.0
altitude = 0.0

[[sensors]]

[sensors.SHWFS]
id = "lgs1"
nsubx = 4
subwidth = 0.2
centre = [0.0, 0.0]
rotation = 0.0
direction = [17.5, 0.0]
gsalt = 90000.0

[[outputs]]
disturbances = ["dm"]
sensors = ["lgs1"]
metric = "WafefrontError"
